In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
df = pd.read_csv('C://Users//Ирина//Downloads//habr_data (2).csv')

In [4]:
df

,Unnamed: 0,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,/ru/articles/734892/,Мультяшная графика продаётся лучше реалистично...,8 мин,Средний,324,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,/ru/articles/734890/,Picture in Picture Mode в android. Показываем ...,5 мин,Простой,122,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,/ru/articles/734888/,"Много нас, а GPU один. Как делиться?",6 мин,Простой,1.6K,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,/ru/articles/734830/,Ближайшие бесплатные мероприятия по разработке...,2 мин,Простой,376,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,/ru/companies/selectel/articles/734860/,Одноплатник Orange Pi 5 Plus: характеристики и...,4 мин,NaN,3.5K,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...,...
995,/ru/articles/728896/,"Java на стероидах, или опыт работы с Jmix",7 мин,Средний,3.3K,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,/ru/companies/sportmaster_lab/articles/728880/,"«Чистый» код, ужасная производительность",16 мин,NaN,54K,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,/ru/articles/723668/,PostgreSQL под капотом. Часть 5. Простой SELEC...,42 мин,NaN,3.2K,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,/ru/articles/728870/,Чат в терминале на Rust,36 мин,Простой,3.4K,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,/ru/articles/728868/,ChatGPT на Java пишет renamer для файлов,4 мин,Простой,2.4K,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [8]:
df.pop('Unnamed: 0')

0                                /ru/articles/734892/
1                                /ru/articles/734890/
2                                /ru/articles/734888/
3                                /ru/articles/734830/
4             /ru/companies/selectel/articles/734860/
                            ...
995                              /ru/articles/728896/
996    /ru/companies/sportmaster_lab/articles/728880/
997                              /ru/articles/723668/
998                              /ru/articles/728870/
999                              /ru/articles/728868/
Name: Unnamed: 0, Length: 1000, dtype: object

In [9]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8 мин,Средний,324,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,Picture in Picture Mode в android. Показываем ...,5 мин,Простой,122,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,"Много нас, а GPU один. Как делиться?",6 мин,Простой,1.6K,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,Ближайшие бесплатные мероприятия по разработке...,2 мин,Простой,376,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4 мин,NaN,3.5K,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7 мин,Средний,3.3K,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,"«Чистый» код, ужасная производительность",16 мин,NaN,54K,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42 мин,NaN,3.2K,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,Чат в терминале на Rust,36 мин,Простой,3.4K,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,ChatGPT на Java пишет renamer для файлов,4 мин,Простой,2.4K,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [10]:
df['Сложность'] = df['Сложность'].fillna(0)

In [11]:
df['Сложность'] = df['Сложность'].replace(['Простой', 'Средний', 'Сложный'],[1, 2, 3])

In [12]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8 мин,2,324,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,Picture in Picture Mode в android. Показываем ...,5 мин,1,122,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,"Много нас, а GPU один. Как делиться?",6 мин,1,1.6K,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,Ближайшие бесплатные мероприятия по разработке...,2 мин,1,376,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4 мин,0,3.5K,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7 мин,2,3.3K,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,"«Чистый» код, ужасная производительность",16 мин,0,54K,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42 мин,0,3.2K,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,Чат в терминале на Rust,36 мин,1,3.4K,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,ChatGPT на Java пишет renamer для файлов,4 мин,1,2.4K,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [13]:
df['Сложность'] = df['Сложность'].replace([0],[','])

In [14]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8 мин,2,324,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,Picture in Picture Mode в android. Показываем ...,5 мин,1,122,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,"Много нас, а GPU один. Как делиться?",6 мин,1,1.6K,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,Ближайшие бесплатные мероприятия по разработке...,2 мин,1,376,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4 мин,",",3.5K,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7 мин,2,3.3K,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,"«Чистый» код, ужасная производительность",16 мин,",",54K,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42 мин,",",3.2K,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,Чат в терминале на Rust,36 мин,1,3.4K,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,ChatGPT на Java пишет renamer для файлов,4 мин,1,2.4K,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [15]:
df[['Время чтения', 'мин']] = df['Время чтения']. str.split(' ', 1 , expand= True )

In [16]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации,мин
0,Мультяшная графика продаётся лучше реалистично...,8,2,324,1,1,@Kallist,0.0,"2023-05-13, 19:20",мин
1,Picture in Picture Mode в android. Показываем ...,5,1,122,3,0,@cookie2727,0.0,"2023-05-13, 18:55",мин
2,"Много нас, а GPU один. Как делиться?",6,1,1.6K,5,6,@Antra,6.1,"2023-05-13, 17:57",мин
3,Ближайшие бесплатные мероприятия по разработке...,2,1,376,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27",мин
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4,",",3.5K,6,13,@Seleditor,49.0,"2023-05-13, 12:55",мин
...,...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7,2,3.3K,20,2,@redcollar,0.0,"2023-04-13, 14:43",мин
996,"«Чистый» код, ужасная производительность",16,",",54K,235,365,@JustJeremy,49.2,"2023-04-13, 14:23",мин
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42,",",3.2K,68,4,@AshBlade,6.5,"2023-04-13, 14:00",мин
998,Чат в терминале на Rust,36,1,3.4K,31,4,@Davydoff33,5.0,"2023-04-13, 13:41",мин
999,ChatGPT на Java пишет renamer для файлов,4,1,2.4K,12,7,@thetka4enko,4.0,"2023-04-13, 13:41",мин

In [17]:
df.pop('мин')

0      мин
1      мин
2      мин
3      мин
4      мин
      ...
995    мин
996    мин
997    мин
998    мин
999    мин
Name: мин, Length: 1000, dtype: object

In [18]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8,2,324,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,Picture in Picture Mode в android. Показываем ...,5,1,122,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,"Много нас, а GPU один. Как делиться?",6,1,1.6K,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,Ближайшие бесплатные мероприятия по разработке...,2,1,376,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4,",",3.5K,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7,2,3.3K,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,"«Чистый» код, ужасная производительность",16,",",54K,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42,",",3.2K,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,Чат в терминале на Rust,36,1,3.4K,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,ChatGPT на Java пишет renamer для файлов,4,1,2.4K,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [19]:
df = df.astype({'Время чтения': np.int64})

In [20]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8,2,324,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,Picture in Picture Mode в android. Показываем ...,5,1,122,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,"Много нас, а GPU один. Как делиться?",6,1,1.6K,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,Ближайшие бесплатные мероприятия по разработке...,2,1,376,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4,",",3.5K,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7,2,3.3K,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,"«Чистый» код, ужасная производительность",16,",",54K,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42,",",3.2K,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,Чат в терминале на Rust,36,1,3.4K,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,ChatGPT на Java пишет renamer для файлов,4,1,2.4K,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [21]:
def value_to_float(x):
    if 'K' in x:
        return float(x.replace('K', '')) * 1000
    else:
        return float(x)
df['Количество просмотров'] =  df['Количество просмотров'].apply(value_to_float)

In [22]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8,2,324.0,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,Picture in Picture Mode в android. Показываем ...,5,1,122.0,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,"Много нас, а GPU один. Как делиться?",6,1,1600.0,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,Ближайшие бесплатные мероприятия по разработке...,2,1,376.0,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4,",",3500.0,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7,2,3300.0,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,"«Чистый» код, ужасная производительность",16,",",54000.0,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42,",",3200.0,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,Чат в терминале на Rust,36,1,3400.0,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,ChatGPT на Java пишет renamer для файлов,4,1,2400.0,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [23]:
df[['Дата публикации', 'Время публикации']] = df['Время публикации']. str.split(' ', 1 , expand= True )

In [24]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации,Дата публикации
0,Мультяшная графика продаётся лучше реалистично...,8,2,324.0,1,1,@Kallist,0.0,19:20,"2023-05-13,"
1,Picture in Picture Mode в android. Показываем ...,5,1,122.0,3,0,@cookie2727,0.0,18:55,"2023-05-13,"
2,"Много нас, а GPU один. Как делиться?",6,1,1600.0,5,6,@Antra,6.1,17:57,"2023-05-13,"
3,Ближайшие бесплатные мероприятия по разработке...,2,1,376.0,1,0,@ITMeeting,-0.8,16:27,"2023-05-13,"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4,",",3500.0,6,13,@Seleditor,49.0,12:55,"2023-05-13,"
...,...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7,2,3300.0,20,2,@redcollar,0.0,14:43,"2023-04-13,"
996,"«Чистый» код, ужасная производительность",16,",",54000.0,235,365,@JustJeremy,49.2,14:23,"2023-04-13,"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42,",",3200.0,68,4,@AshBlade,6.5,14:00,"2023-04-13,"
998,Чат в терминале на Rust,36,1,3400.0,31,4,@Davydoff33,5.0,13:41,"2023-04-13,"
999,ChatGPT на Java пишет renamer для файлов,4,1,2400.0,12,7,@thetka4enko,4.0,13:41,"2023-04-13,"

In [29]:
df['Дата публикации'] = pd.to_datetime(df['Дата публикации'])

In [30]:
df['Время публикации'] = pd.to_datetime(df['Время публикации'])

In [31]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации,Дата публикации
0,Мультяшная графика продаётся лучше реалистично...,8,2,324.0,1,1,@Kallist,0.0,2023-06-06 19:20:00,2023-05-13
1,Picture in Picture Mode в android. Показываем ...,5,1,122.0,3,0,@cookie2727,0.0,2023-06-06 18:55:00,2023-05-13
2,"Много нас, а GPU один. Как делиться?",6,1,1600.0,5,6,@Antra,6.1,2023-06-06 17:57:00,2023-05-13
3,Ближайшие бесплатные мероприятия по разработке...,2,1,376.0,1,0,@ITMeeting,-0.8,2023-06-06 16:27:00,2023-05-13
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4,",",3500.0,6,13,@Seleditor,49.0,2023-06-06 12:55:00,2023-05-13
...,...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7,2,3300.0,20,2,@redcollar,0.0,2023-06-06 14:43:00,2023-04-13
996,"«Чистый» код, ужасная производительность",16,",",54000.0,235,365,@JustJeremy,49.2,2023-06-06 14:23:00,2023-04-13
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42,",",3200.0,68,4,@AshBlade,6.5,2023-06-06 14:00:00,2023-04-13
998,Чат в терминале на Rust,36,1,3400.0,31,4,@Davydoff33,5.0,2023-06-06 13:41:00,2023-04-13
999,ChatGPT на Java пишет renamer для файлов,4,1,2400.0,12,7,@thetka4enko,4.0,2023-06-06 13:41:00,2023-04-13

In [34]:
df.to_csv("habr_cleared_data")