In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C://Users//Ирина//Downloads//habr_data (2).csv')

In [3]:
# удаляю ненужную колонку
df.pop('Unnamed: 0')

0                                /ru/articles/734892/
1                                /ru/articles/734890/
2                                /ru/articles/734888/
3                                /ru/articles/734830/
4             /ru/companies/selectel/articles/734860/
                            ...
995                              /ru/articles/728896/
996    /ru/companies/sportmaster_lab/articles/728880/
997                              /ru/articles/723668/
998                              /ru/articles/728870/
999                              /ru/articles/728868/
Name: Unnamed: 0, Length: 1000, dtype: object

In [4]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8 мин,Средний,324,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,Picture in Picture Mode в android. Показываем ...,5 мин,Простой,122,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,"Много нас, а GPU один. Как делиться?",6 мин,Простой,1.6K,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,Ближайшие бесплатные мероприятия по разработке...,2 мин,Простой,376,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4 мин,NaN,3.5K,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7 мин,Средний,3.3K,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,"«Чистый» код, ужасная производительность",16 мин,NaN,54K,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42 мин,NaN,3.2K,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,Чат в терминале на Rust,36 мин,Простой,3.4K,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,ChatGPT на Java пишет renamer для файлов,4 мин,Простой,2.4K,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [5]:
# заменяю пустые значения на 0
df['Сложность'] = df['Сложность'].fillna(0)

# делаю кодировку 
df['Сложность'] = df['Сложность'].replace(['Простой', 'Средний', 'Сложный'],[1, 2, 3])

In [6]:
# меняю 0 на запятые, чтобы не влияли на значения
df['Сложность'] = df['Сложность'].replace([0],[','])

# превращаю численно-буквенный вид в численный
df[['Время чтения', 'мин']] = df['Время чтения']. str.split(' ', 1 , expand= True )
df.pop('мин')
df = df.astype({'Время чтения': np.int64})

In [7]:
# "К" превращаю в тысячи
def value_to_float(x):
    if 'K' in x:
        return float(x.replace('K', '')) * 1000
    else:
        return float(x)
df['Количество просмотров'] =  df['Количество просмотров'].apply(value_to_float)

In [8]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8,2,324.0,1,1,@Kallist,0.0,"2023-05-13, 19:20"
1,Picture in Picture Mode в android. Показываем ...,5,1,122.0,3,0,@cookie2727,0.0,"2023-05-13, 18:55"
2,"Много нас, а GPU один. Как делиться?",6,1,1600.0,5,6,@Antra,6.1,"2023-05-13, 17:57"
3,Ближайшие бесплатные мероприятия по разработке...,2,1,376.0,1,0,@ITMeeting,-0.8,"2023-05-13, 16:27"
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4,",",3500.0,6,13,@Seleditor,49.0,"2023-05-13, 12:55"
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7,2,3300.0,20,2,@redcollar,0.0,"2023-04-13, 14:43"
996,"«Чистый» код, ужасная производительность",16,",",54000.0,235,365,@JustJeremy,49.2,"2023-04-13, 14:23"
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42,",",3200.0,68,4,@AshBlade,6.5,"2023-04-13, 14:00"
998,Чат в терминале на Rust,36,1,3400.0,31,4,@Davydoff33,5.0,"2023-04-13, 13:41"
999,ChatGPT на Java пишет renamer для файлов,4,1,2400.0,12,7,@thetka4enko,4.0,"2023-04-13, 13:41"

In [10]:
# превращаю в дататайм
df['Время публикации'] = pd.to_datetime(df['Время публикации'])

In [11]:
df

,item name,Время чтения,Сложность,Количество просмотров,В закладках,Комментарии,Автор,Рейтинг автора,Время публикации
0,Мультяшная графика продаётся лучше реалистично...,8,2,324.0,1,1,@Kallist,0.0,2023-05-13 19:20:00
1,Picture in Picture Mode в android. Показываем ...,5,1,122.0,3,0,@cookie2727,0.0,2023-05-13 18:55:00
2,"Много нас, а GPU один. Как делиться?",6,1,1600.0,5,6,@Antra,6.1,2023-05-13 17:57:00
3,Ближайшие бесплатные мероприятия по разработке...,2,1,376.0,1,0,@ITMeeting,-0.8,2023-05-13 16:27:00
4,Одноплатник Orange Pi 5 Plus: характеристики и...,4,",",3500.0,6,13,@Seleditor,49.0,2023-05-13 12:55:00
...,...,...,...,...,...,...,...,...,...
995,"Java на стероидах, или опыт работы с Jmix",7,2,3300.0,20,2,@redcollar,0.0,2023-04-13 14:43:00
996,"«Чистый» код, ужасная производительность",16,",",54000.0,235,365,@JustJeremy,49.2,2023-04-13 14:23:00
997,PostgreSQL под капотом. Часть 5. Простой SELEC...,42,",",3200.0,68,4,@AshBlade,6.5,2023-04-13 14:00:00
998,Чат в терминале на Rust,36,1,3400.0,31,4,@Davydoff33,5.0,2023-04-13 13:41:00
999,ChatGPT на Java пишет renamer для файлов,4,1,2400.0,12,7,@thetka4enko,4.0,2023-04-13 13:41:00

In [12]:
df.to_csv("habr_cleared_data.csv")